### ISSUE TITLE
Explanation of collected data

### ISSUE THREAD

**Issue by mpardalos** [leoratte/aquacomputer-quadro-control#1]
I'm interested in working on figuring out the checksum algorithm. It would be very useful to have some notes on what you have figured out about the aquacomputer quadro protocol. 

A dump of any notes you might have would be great, but really I would also just appreciate a short explanation.

**Comment by leoratte** [comment]
I added some information on the data i already collected and a few links to resources about CRC.
I hope this already helps you. Contact me again if you need anything more specific.
